import Head from 'next/head'
import { useState, useEffect } from 'react'


export default function Home() {
  const [todos, setTodos] = useState([]);

  const [journalStatus, setJournalStatus] = useState(""); 
  const [falseStatusTodosCount, setFalseStatusTodosCount] = useState(0);
  const [projectCount, setProjectCount] = useState(0);

  useEffect(() => {
    const storedJournals = localStorage.getItem('journals');
    const storedTodos = localStorage.getItem('todos');
    const storedValues = localStorage.getItem('value');
    const today = new Date().toISOString().split('T')[0]; 

    if (storedJournals) {
      const journals = JSON.parse(storedJournals);
      const hasTodaysJournal = journals.filter(journal => {
        const journalDate = new Date(journal.date).toISOString().split('T')[0]; // วันที่ของ Journal
        return journalDate === today;
      }).length > 0;

      if (hasTodaysJournal) {
        setJournalStatus("You've written the Journal.");
      } else {
        setJournalStatus("You haven't written a journal yet.");
      }
    }

    if (storedTodos) {
      const parsedTodos = JSON.parse(storedTodos);
      setTodos(parsedTodos);

      const falseStatusTodos = parsedTodos.filter(todo => todo.status === false);
      setFalseStatusTodosCount(falseStatusTodos.length);
    }
  
    if (storedValues) {
      const parsedValues = JSON.parse(storedValues);
  
    
      const currentDate = new Date();
      const start = currentDate.toISOString().split('T')[0];
      const end = new Date(currentDate.getTime() + (24 * 60 * 60 * 1000)).toISOString().split('T')[0]; 
  
   
      const filteredValues = parsedValues.filter(value => {
   
        return value.start <= start && value.end >= end;
      });
  
      setProjectCount(filteredValues.length);
    }

  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>
        <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
      </Head>



      <h1>Wellcome to your management, Maomao </h1>
      
      <div className='home'>
        <div className='box'>
          <div className='home-content'>
            <h3>Calendars</h3>
            <center><div>{projectCount}</div></center>
          </div>

        </div>
        <div className='box'>
          <div className='home-content'>
            <h3>To do lists</h3>
            <center><div>{falseStatusTodosCount}</div></center>
          </div>
        </div>
        <div className='box'>
          <div className='home-content'>
          <center><h3>Journals</h3></center>
            <center><div>{journalStatus}</div></center>
          </div>
        </div>
      </div>




    </>
  )
}
